name: Un workflow para mi action de fibonacci
on: push
 
jobs:
  build:
    name: Correr fibonacci action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./fibonacci
        with:
          N_INDEX: "9"
          